name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-2025-vs2026   # 👈 Windows use ho raha hai

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build
